const SETTOKEN = 'SETTOKEN';
const LOADING = 'LOADING';
const ERRORMESSAGE = 'ERRORMESSAGE';
const LOGOUT = 'LOGOUT';
const SETUSERDATA = 'SETUSERDATA';
const SETUSERSLIST = 'SETUSERSLIST';
const TRANSFER = 'TRANSFER';
const TRANSACTIONERROR = 'TRANSACTIONERROR';
const SENT = 'SENT';

export {
    SETTOKEN,
    LOADING,
    ERRORMESSAGE,
    LOGOUT,
    SETUSERDATA,
    SETUSERSLIST,
    TRANSFER,
    TRANSACTIONERROR,
    SENT
}